import { useEffect, useState } from "react";

import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Toolbar from "@/components/Navigation/Toolbar/Toolbar";
import { getSession } from "next-auth/react";
import { getToken } from "next-auth/jwt";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [userData, setUserData] = useState(null);
  const [leaderData, setLeaderData] = useState(null);

  useEffect(() => {
    async function getUserData() {
      let response = await getSession();
      response = await response;
      setUserData(response);
      return userData;
    }

    async function prepLeader() {
      let response = await getSession();
      response = await response;
      if (response) {
        const jwt = response.accessToken;
        console.log("jwt: ", jwt);

        let leaderResponse = await fetch(
          "https://admin.rbcommunity.org/leader-groups",
          {
            headers: { Authorization: `Bearer ${jwt}` },
          }
        );

        leaderResponse = await leaderResponse.json();
        setLeaderData(leaderResponse);
      }
    }

    getUserData();
    prepLeader();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />
      <main>
        <h1>Welcome to RB Community Church's Leader Site</h1>
        <div>
          {leaderData ? <h2>Elders</h2> : null}

          {leaderData
            ? leaderData[0].users.map((elder) => (
                <div style={{ marginBottom: "2rem" }} key={elder.id}>
                  <div>{`${elder.firstName} ${elder.lastName}`}</div>
                  <div>{elder.address}</div>
                  <div>{`${elder.city}, CA ${elder.zipCode}`}</div>
                  <div style={{ marginTop: ".33rem" }}>
                    Cell Phone: {elder.cellPhone}
                  </div>
                  <div>Home Phone: {elder.homePhone}</div>
                  <a href={`mailto:${elder.email}`}>{elder.email}</a>
                  <div>Area of responsibility: {elder.responsibility}</div>
                </div>
              ))
            : null}
        </div>
      </main>
    </>
  );
}
